# -*- coding: utf-8 -*-
"""Breast Cancer Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mPEx6Bbr5X3Yf393AfuAJfAMzDnU9W60

Importing the dependencies
"""

import numpy as np
import pandas as pd
import sklearn.datasets
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

"""Data Collection & Processing"""

breast_cancer_dataset = sklearn.datasets.load_breast_cancer()
print(breast_cancer_dataset)

data_frame=pd.DataFrame(breast_cancer_dataset.data,columns=breast_cancer_dataset.feature_names)

data_frame.head()

data_frame['label']=breast_cancer_dataset.target

data_frame.head()

data_frame.tail()

data_frame.info()

data_frame.describe()

data_frame['label'].value_counts()

"""**1 represents Benign**

**0 represents malignant**
"""

data_frame.groupby('label').mean()



"""Seprating the features and the target"""

X=data_frame.drop(columns='label',axis=1)
Y=data_frame['label']

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=1)

print(X.shape,X_train.shape,X_test.shape)

"""Model Training"""

model = LogisticRegression()

model.fit(X_train,Y_train)

"""Model Evaluation"""

X_train_prediction=model.predict(X_train)
train_data_accuracy=accuracy_score(Y_train,model.predict(X_train))

print("Accuracy on training data : ",train_data_accuracy)

X_test_prediction=model.predict(X_test)
test_data_accuracy=accuracy_score(Y_test,model.predict(X_test))

print("Accuracy on test data : ",test_data_accuracy)

"""Predictive System"""

input_data = (17.99,10.38,122.8,1001,0.1184,0.2776,0.3001,0.1471,0.2419,0.07871,1.095,0.9053,8.589,153.4,0.006399,0.04904,0.05373,0.01587,0.03003,0.006193,25.38,17.33,184.6,2019,0.1622,0.6656,0.7119,0.2654,0.4601,0.1189)

input_data_as_numpy_array=np.asarray(input_data)

input_data_reshaped=input_data_as_numpy_array.reshape(1,-1)

prediction = model.predict(input_data_reshaped)

if(prediction[0]==0):
  print("The Breast Cancer is Malignant")
else:
  print("The Breast Cancer is Benign")

